services:
  xboard:
    build:
      context: .
      args:
        REPO_URL: ${XBOARD_REPO_URL:-https://github.com/wind951017/Xboard}
        BRANCH_NAME: ${XBOARD_BRANCH:-master}
    image: ${XBOARD_IMAGE:-wind951017/xboard:distribution}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./.env:/www/.env
      - ./.docker/.data/:/www/.docker/.data
      - ./storage/logs:/www/storage/logs
      - ./storage/theme:/www/storage/theme
      - ./plugins:/www/plugins
      - redis-data:/data
    environment:
      - RESOURCE_PROFILE=balanced      # minimal | balanced | performance | auto
      - ENABLE_HORIZON=true
      - docker=true

volumes:
  redis-data:
